print("Hello Pong")
print('Update')
print('Update')
print('Update')
print('Update')
print('Update')
print('Update')
print('Update')
print('Update')
print('Update')
print('Update')
print('Update')
print('Update')
print('Update')